project:
  description: "Development Department service from config-server from github"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    register-with-eureka: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
#  output:
#    ansi:
#      enabled: always


management:
  tracing:
    sampling:
      probability: 1.0

feign:
  client:
    config:
      default:
        read-timeout: 5000
        metrics:
          enabled: true
        logger-level: full
        connectTimeout: 5000
