project:
  description: "Development Organization service from config-server from github"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always


management:
  tracing:
    sampling:
      probability: 1.0

feign:
  client:
    config:
      default:
        read-timeout: 5000
        metrics:
          enabled: true
        logger-level: full
        connectTimeout: 5000
